stages:
  - build

build:
  image: node:latest    # Run the job in a `node` docker image
  stage: build
  script:
    - yarn install      # Run `yarn install` and `yarn build`
    - yarn build
  artifacts:
    paths:
      - build/          # Save the build result as an artfact
      variables:
  GIT_STRATEGY: none
  GIT_CLONE_PATH: ""
  PAGES_HTTP_ONLY: "true"